### ISSUE TITLE
Translation attribute cannot bind to main model when call .toJSON()

### ISSUE THREAD

**Issue by khanhdn-gem** [emilioforrer/adonis-translatable#1]
Firstly, thanks for your great code :)

I have an issue when use this package: the translation attributes cannot bind to main model when call .toJSON() method

For example:
`
const result = Role.all()
const roles = result.toJSON()
`

roles does not have `name` attribute

I have to access to `roles.translation.name` to get value

Could you help me?

**Comment by emilioforrer** [comment]
Hi!
Thank you so much for reporting this issue.
It is now fixed in a new release v1.0.1.
